export const SET_PROFILES = 'SET_PROFILES';
export const SET_REVIEWS = 'SET_REVIEWS';

export const SET_ACTIVE_PROFILE = 'SET_ACTIVE_PROFILE';
export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';

export const SET_PROFILE = 'SET_PROFILE';
export const SET_REVIEW = 'SET_REVIEW';

export const DELETE_PROFILE = 'DELETE_PROFILE';
export const DELETE_REVIEW = 'DELETE_REVIEW';
